Fixing stuff for 14are05

diff --git a/battmngr b/battmngr
--- a/battmngr
+++ b/battmngr
@@ -11,21 +11,20 @@
 ## Battery modes:
 ##	1	Intelligent Cooling
 ##	2	Extreme Performance
-##	3	Battery Saving	
-##	
+##	3	Battery Saving
+##
 ## Charge modes:
 ##	1	Rapid Charge On
 ##	2	Rapid Charge Off
 ##	3	Battery Conservation On
-##	4	Battery Conservation Off		
+##	4	Battery Conservation Off
 ##
 ## Examples:
-## 	battmngr -r 
+## 	battmngr -r
 ## 	battmngr -s 1
 ##	battmngr -rc
 ##	battmngr -sc 1
 ##	battmngr -s 1 -r -sc 4 -rc
-
 
 #######################################
 # Print error messages to STDERR.
@@ -36,8 +35,8 @@
 # Outputs:
 #   Writes error message to STDERR
 #######################################
-err(){
-  echo "$*" >&2
+err() {
+	echo "$*" >&2
 }
 
 #######################################
@@ -49,30 +48,30 @@ err(){
 # Outputs:
 #   Writes usage message to STDOUT
 #######################################
-usage(){
-	printf '%s\n'\
-	""\
-	"Usage: battmngr [OPTION...] MODE"\
-	"Options:"\
-	"        -r, --read             read current battery mode"\
-	"        -s, --set              set battery mode"\
-	"        -rc, --read-charge     read current charge mode"\
-	"        -sc, --set-charge      set charge mode"\
-	"Battery Modes:"\
-	"        1        Intelligent Cooling"\
-	"        2        Extreme Performance"\
-	"        3        Battery Saving"\
-	"Charge modes:"\
-	"        1        Rapid Charge On"\
-	"        2        Rapid Charge Off"\
-	"        3        Battery Conservation On"\
-	"        4        Battery Conservation Off"\
-	"Examples:"\
-	"        battmngr -r "\
-	"        battmngr -s 1"\
-	"        battmngr -rc"\
-	"        battmngr -sc 1"\
-	"        battmngr -s 1 -r -sc 4 -rc"
+usage() {
+	printf '%s\n' \
+		"" \
+		"Usage: battmngr [OPTION...] MODE" \
+		"Options:" \
+		"        -r, --read             read current battery mode" \
+		"        -s, --set              set battery mode" \
+		"        -rc, --read-charge     read current charge mode" \
+		"        -sc, --set-charge      set charge mode" \
+		"Battery Modes:" \
+		"        1        Intelligent Cooling" \
+		"        2        Extreme Performance" \
+		"        3        Battery Saving" \
+		"Charge modes:" \
+		"        1        Rapid Charge On" \
+		"        2        Rapid Charge Off" \
+		"        3        Battery Conservation On" \
+		"        4        Battery Conservation Off" \
+		"Examples:" \
+		"        battmngr -r " \
+		"        battmngr -s 1" \
+		"        battmngr -rc" \
+		"        battmngr -sc 1" \
+		"        battmngr -s 1 -r -sc 4 -rc"
 }
 
 #######################################
@@ -84,58 +83,58 @@ usage(){
 # Outputs:
 #   None
 #######################################
-function error(){
+function error() {
 	case $1 in
 
-		0)
-			err "Please provide a valid battery mode to set (only 1,2 and 3 are valid values)"
-			usage
-		;;
-		
-		1)
-			err "Please provide a valid battery charge mode to set (only 1,2,3 and 4 are valid values)"
-			usage
+	0)
+		err "Please provide a valid battery mode to set (only 1,2 and 3 are valid values)"
+		usage
 		;;
 
-		2)
-			err "Can't update the battery mode, please retry"
-		;;
-		
-		3)
-			err "Can't update the battery charge mode, please retry"
-		;;
-		
-		4)
-			err "Unrecognized battery mode, please retry"
-		;;
-		
-		5)
-			err "Unrecognized battery charge mode, please retry"
+	1)
+		err "Please provide a valid battery charge mode to set (only 1,2,3 and 4 are valid values)"
+		usage
 		;;
 
-		7)
-			err "Unrecognized operation"
-			usage
+	2)
+		err "Can't update the battery mode, please retry"
 		;;
 
-		8)
-			err "Please specify an operation"
-			usage
-		;;
-		
-		9)
-			err "Unexpected error"
-		;;
-		
-		10) 	
-			err "Please invoke this script using sudo"
+	3)
+		err "Can't update the battery charge mode, please retry"
 		;;
 
-		*)
-			err "Unknown error"
+	4)
+		err "Unrecognized battery mode, please retry"
+		;;
+
+	5)
+		err "Unrecognized battery charge mode, please retry"
+		;;
+
+	7)
+		err "Unrecognized operation"
+		usage
+		;;
+
+	8)
+		err "Please specify an operation"
+		usage
+		;;
+
+	9)
+		err "Unexpected error"
+		;;
+
+	10)
+		err "Please invoke this script using sudo"
+		;;
+
+	*)
+		err "Unknown error"
 		;;
 	esac
-	
+
 	exit 1
 }
 
@@ -148,10 +147,10 @@ function error(){
 # Outputs:
 #   None
 #######################################
-function check_sudo(){
-	if (( $(id -u) != 0 )); then
+function check_sudo() {
+	if (($(id -u) != 0)); then
 		error 10
-	fi;
+	fi
 }
 
 #######################################
@@ -163,31 +162,12 @@ function check_sudo(){
 # Outputs:
 #   None
 #######################################
-function setup(){
+function setup() {
 	modprobe acpi_call
 }
 
 #######################################
-# Reads the current mode and check if 
-# it's equal to the expected one.
-# Globals:
-#   None
-# Arguments:
-#   Expected mode code
-# Outputs:
-#   None
-#######################################
-function check_mode(){
-	echo '\_SB.PCI0.LPC0.EC0.SPMO' > /proc/acpi/call
-	check=$(cat /proc/acpi/call | cut -d '' -f1)
-
-	if ! (( $check == $1 )); then
-		error 2
-	fi
-}
-
-#######################################
-# Reads the current charge mode and 
+# Reads the current charge mode and
 # check if it's equal to the expected one.
 # Globals:
 #   None
@@ -197,23 +177,19 @@ function check_mode(){
 # Outputs:
 #   None
 #######################################
-function check_charge_mode(){
+function check_charge_mode() {
 	# if we are checking rapid charge mode
-	if (( $1 == 0 )); then
-		echo '\_SB.PCI0.LPC0.EC0.QCHO' > /proc/acpi/call
+	if (($1 == 0)); then
+		echo '\_SB.PCI0.LPC0.EC0.FCGM' >/proc/acpi/call
 		check=$(cat /proc/acpi/call | cut -d '' -f1)
-		
+
 	# if we are checking battery conservation mode
-	elif (( $1 == 1 )); then
-		echo '\_SB.PCI0.LPC0.EC0.BTSM' > /proc/acpi/call
+	elif (($1 == 1)); then
+		echo '\_SB.PCI0.LPC0.EC0.BTSG' >/proc/acpi/call
 		check=$(cat /proc/acpi/call | cut -d '' -f1)
 	else
 		# unexpected error!
 		error 9
-	fi
-
-	if ! (( $check == $2 )); then
-		error 3
 	fi
 }
 
@@ -226,29 +202,26 @@ function check_charge_mode(){
 # Outputs:
 #   None
 #######################################
-function set_operation(){
+function set_operation() {
 	case $1 in
 
-		1)
-			# Intelligent Cooling 
-			echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x000FB001' > /proc/acpi/call
-			check_mode "0x0"
+	1)
+		# Intelligent Cooling
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x000FB001' >/proc/acpi/call
 		;;
 
-		2)
-			# Extreme Performance 
- 			echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x0012B001' > /proc/acpi/call
- 			check_mode "0x1"
+	2)
+		# Extreme Performance
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x0012B001' >/proc/acpi/call
 		;;
 
-		3)
-			# Battery Saving
-			echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x0013B001' > /proc/acpi/call
-			check_mode "0x2"
+	3)
+		# Battery Saving
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.DYTC 0x0013B001' >/proc/acpi/call
 		;;
 
-		*)
-			error 9
+	*)
+		error 9
 		;;
 	esac
 }
@@ -262,35 +235,35 @@ function set_operation(){
 # Outputs:
 #   None
 #######################################
-function set_charge_operation(){
+function set_charge_operation() {
 	case $1 in
 
-		1)
-			# Rapid Charge On
-			echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x07' > /proc/acpi/call
-			check_charge_mode 0 "0x1"
+	1)
+		# Rapid Charge On
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x07' >/proc/acpi/call
+		check_charge_mode 0 "0x1"
 		;;
 
-		2)
-			# Rapid Charge Off 
- 			echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' > /proc/acpi/call
- 			check_charge_mode 0 "0x0"
+	2)
+		# Rapid Charge Off
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' >/proc/acpi/call
+		check_charge_mode 0 "0x0"
 		;;
 
-		3)
-			# Battery Conservation On
-			echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x03' > /proc/acpi/call
-			check_charge_mode 1 "0x1"
-		;;
-		
-		4)
-			# Battery Conservation Off
-			echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x05' > /proc/acpi/call
-			check_charge_mode 1 "0x0"
+	3)
+		# Battery Conservation On
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x03' >/proc/acpi/call
+		check_charge_mode 1 "0x1"
 		;;
 
-		*)
-			error 9
+	4)
+		# Battery Conservation Off
+		echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x05' >/proc/acpi/call
+		check_charge_mode 1 "0x0"
+		;;
+
+	*)
+		error 9
 		;;
 	esac
 
@@ -305,29 +278,35 @@ function set_charge_operation(){
 # Outputs:
 #   Print battery mode name on STDOUT
 #######################################
-function read_operation(){
-	echo '\_SB.PCI0.LPC0.EC0.SPMO' > /proc/acpi/call
+function read_operation() {
+	echo '\_SB.PCI0.LPC0.EC0.STMD' >/proc/acpi/call
 	check=$(cat /proc/acpi/call | cut -d '' -f1)
 
+	echo '\_SB.PCI0.LPC0.EC0.QTMD' >/proc/acpi/call
+	check2=$(cat /proc/acpi/call | cut -d '' -f1)
 	case $check in
 
+	"0x0")
+		case $check2 in
 		"0x0")
-			echo "Intelligent Cooling"
-		;;
+			echo "Extreme Performance"
+			;;
 
 		"0x1")
-			echo "Extreme Performance"
-		;;
-
-		"0x2")
 			echo "Battery Saving"
+			;;
+		esac
 		;;
 
-		*)
-			error 4
+	"0x1")
+		echo "Intelligent Cooling"
+		;;
+
+	*)
+		error 4
 		;;
 	esac
-	
+
 }
 
 #######################################
@@ -339,42 +318,42 @@ function read_operation(){
 # Outputs:
 #   Print battery charge mode names on STDOUT
 #######################################
-function read_charge_operation(){
+function read_charge_operation() {
 	# rapid charge check
-	echo '\_SB.PCI0.LPC0.EC0.QCHO' > /proc/acpi/call
+	echo '\_SB.PCI0.LPC0.EC0.FCGM' >/proc/acpi/call
 	check=$(cat /proc/acpi/call | cut -d '' -f1)
 
 	case $check in
 
-		"0x0")
-			echo "Rapid Charge Off"
+	"0x0")
+		echo "Rapid Charge Off"
 		;;
 
-		"0x1")
-			echo "Rapid Charge On"
+	"0x1")
+		echo "Rapid Charge On"
 		;;
 
-		*)
-			error 5
+	*)
+		error 5
 		;;
 	esac
-	
+
 	# battery conservation check
-	echo '\_SB.PCI0.LPC0.EC0.BTSM' > /proc/acpi/call
+	echo '\_SB.PCI0.LPC0.EC0.BTSG' >/proc/acpi/call
 	check=$(cat /proc/acpi/call | cut -d '' -f1)
 
 	case $check in
 
-		"0x0")
-			echo "Battery Conservation Off"
+	"0x0")
+		echo "Battery Conservation Off"
 		;;
 
-		"0x1")
-			echo "Battery Conservation On"
+	"0x1")
+		echo "Battery Conservation On"
 		;;
 
-		*)
-			error 5
+	*)
+		error 5
 		;;
 	esac
 }
@@ -388,83 +367,79 @@ setup
 if [ -z "$1" ]; then
 	error 8
 fi
-	
+
 while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -s|--set)  
-        	# set operation
-        	
+	case $1 in
+	-s | --set)
+		# set operation
+
 		# check if there is a parameter
-		if [ ! -z "$2" ]; then 
+		if [ ! -z "$2" ]; then
 			# if it's not numeric calls error
 			if ! [[ $2 =~ ^[0-9]+$ ]]; then
 				error 0
 			fi
-			
+
 			# if the parameter is good, set param
-	  		if (($2 >= 0 && $2 <= 3));  then
+			if (($2 >= 0 && $2 <= 3)); then
 				set_operation $2
-				
+
 			# if it's not in the expected range calls error
-			else 
+			else
 				error 0
 			fi
 			shift
-		
+
 		# if there is no parameter calls error
 		else
 			error 0
 		fi
-        	shift
-        	;;
-        	
-        -r|--read) 
-        	# read mode
+		shift
+		;;
+
+	-r | --read)
+		# read mode
 		read_operation
 		shift
 		;;
-        	
-        -sc|--set-charge)  
-        	# set charge operation
-        
+
+	-sc | --set-charge)
+		# set charge operation
+
 		# check if there is a parameter
-		if [ ! -z "$2" ]; then 
+		if [ ! -z "$2" ]; then
 			# if it's not numeric calls error
 			if ! [[ $2 =~ ^[0-9]+$ ]]; then
 				error 1
 			fi
-			
+
 			# if the parameter is good, set param
-	  		if (($2 >= 0 && $2 <= 4));  then
+			if (($2 >= 0 && $2 <= 4)); then
 				set_charge_operation $2
-				
+
 			# if it's not in the expected range calls error
-			else 
+			else
 				error 1
 			fi
 			shift
-		
+
 		# if there is no parameter calls error
-		else 
+		else
 			error 1
 		fi
-        	shift
-        	;;
-        	
-        -rc|--read-charge) 
-        	# read charge mode
-        	read_charge_operation
-        	shift
-        	;;
-        	
-        *) 
-        	error 7
-        	;;
-    esac
-    
+		shift
+		;;
+
+	-rc | --read-charge)
+		# read charge mode
+		read_charge_operation
+		shift
+		;;
+
+	*)
+		error 7
+		;;
+	esac
+
 done
 exit 0
-
-
-
-
